In [15]:
import pandas as pd
import numpy as np

In [16]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

In [17]:
df = pd.read_csv('train.csv')[['Age', 'Fare','SibSp', 'Parch', 'Survived']]

In [18]:
df.dropna(inplace=True)

In [19]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [20]:
df['family'] = df['SibSp'] + df['Parch']

In [21]:
df.sample()

      Age   Fare  SibSp  Parch  Survived  family
244  30.0  7.225      0      0         0       0

In [26]:
X=df.drop(columns=['Survived'])
y = df['Survived']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
# without binarization

clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_pred, y_test)

0.6363636363636364

In [29]:
np.mean(cross_val_score(DecisionTreeClassifier(), X, y, cv=10, scoring='accuracy'))

0.6345266040688576

In [30]:
from sklearn.preprocessing import Binarizer

In [36]:
trf = ColumnTransformer([
    ('bin', Binarizer(copy=False), ['family'])
], remainder='passthrough')

In [37]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [39]:
X_train_trf_df = pd.DataFrame(
    X_train_trf,
    columns=['family', 'Age', 'Fare']
)

ValueError: Shape of passed values is (571, 5), indices imply (571, 3)

In [40]:
# without binarization

clf = DecisionTreeClassifier()

clf.fit(X_train_trf, y_train)

y_pred = clf.predict(X_test_trf)

accuracy_score(y_pred, y_test)

0.6223776223776224

In [41]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(), X, y, cv=10, scoring='accuracy'))

0.6372065727699531