In [2]:
import pandas as pd
import numpy as np

In [3]:
date = pd.read_csv('../__datasets__/orders.csv')
time = pd.read_csv('../__datasets__/messages.csv')

In [5]:
date.sample(5)

           date  product_id  city_id  orders
424  2019-10-12         637       26       1
370  2019-01-23        4573        2       3
461  2019-10-20        5125        3       3
353  2018-08-08        2284        9       8
418  2019-07-16        3553        0       1

In [6]:
time.sample(5)

                    date                                                msg
22   2015-02-18 00:34:00  ищю д-ж для и от30до60 сначала смс админ 226(0...
516  2014-11-29 01:21:00        пообщаюсь с ласковой кошечкой 067 560 10 95
33   2015-07-03 00:45:00  п+п познакомится30-45 звонить завтра после10 ....
202  2012-07-29 23:31:00                         Витаха Дндз братанчик с дн
184  2013-07-02 22:41:00                                           дима аня

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [10]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Working with dates

In [11]:
# converting to datetime datatypes
date['date'] = pd.to_datetime(date['date'])

In [12]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## Extracting Year

In [13]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
597 2018-10-18        4846        1       1       2018
988 2019-02-03        5022        2      43       2019
230 2018-07-22        7554       13      12       2018
713 2018-10-14        4269       22       2       2018
764 2019-07-26        6850        1       2       2019

## Extacting Month

In [14]:
date['date_month'] = date['date'].dt.month

date.sample(5)

          date  product_id  city_id  orders  date_year  date_month
898 2019-02-20        2945       22       2       2019           2
342 2019-07-31        4509       22       4       2019           7
862 2018-11-03        1404       21       1       2018          11
418 2019-07-16        3553        0       1       2019           7
601 2019-11-24        6592       25      12       2019          11

## Extracting Month by name

In [16]:
date['Month'] = date['date'].dt.month_name()
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month     Month
439 2019-11-21        7224       25       1       2019          11  November
543 2019-12-05        3944       13       1       2019          12  December
95  2019-04-02        5383       11      24       2019           4     April
477 2018-08-08         383       25      22       2018           8    August
645 2019-02-11        6091       25      40       2019           2  February

## Extracting Days

In [20]:
date['day'] = date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,Month,day
829,2019-09-18,287,6,4,2019,9,September,18
285,2018-10-19,6619,4,1,2018,10,October,19
969,2019-11-28,1307,1,9,2019,11,November,28
579,2018-08-13,7059,14,31,2018,8,August,13
902,2019-03-24,5031,0,6,2019,3,March,24

## Extracting which day of week

In [21]:
date['dayno'] = date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,Month,day,dayno
979,2019-08-19,2426,22,1,2019,8,August,19,0
220,2019-12-14,4482,28,2,2019,12,December,14,5
7,2019-03-27,5022,2,41,2019,3,March,27,2
236,2018-08-24,4576,22,3,2018,8,August,24,4
435,2018-10-20,4847,26,9,2018,10,October,20,5

## Extracting Day Name

In [22]:
date['DayName'] = date['date'].dt.day_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,Month,day,dayno,DayName
144,2019-10-14,5778,24,108,2019,10,October,14,0,Monday
741,2019-11-10,7318,25,1,2019,11,November,10,6,Sunday
241,2019-07-25,582,26,8,2019,7,July,25,3,Thursday
10,2019-10-24,6339,26,1,2019,10,October,24,3,Thursday
480,2019-02-06,3835,9,2,2019,2,February,6,2,Wednesday

## Extracting weekends

In [25]:
date['weekends'] = np.where(date['DayName'].isin(['Sunday', 'Saturday']), 1, 0)
date.sample(3)

,date,product_id,city_id,orders,date_year,date_month,Month,day,dayno,DayName,weekends
175,2018-09-04,3125,1,10,2018,9,September,4,1,Tuesday,0
451,2018-12-23,7078,22,6,2018,12,December,23,6,Sunday,1
374,2018-12-16,4595,13,1,2018,12,December,16,6,Sunday,1

## Extract week of the year

In [28]:
date['weekNo'] = date['date'].dt.isocalendar().week
date.sample(3)

,date,product_id,city_id,orders,date_year,date_month,Month,day,dayno,DayName,weekends,weekNo
521,2018-08-23,5482,25,7,2018,8,August,23,3,Thursday,0,34
666,2019-03-19,7429,13,1,2019,3,March,19,1,Tuesday,0,12
379,2019-10-11,2381,18,23,2019,10,October,11,4,Friday,0,41

## Extract Quarter

In [31]:
date['Quarter'] = date['date'].dt.quarter
date.sample(3)

,date,product_id,city_id,orders,date_year,date_month,Month,day,dayno,DayName,weekends,weekNo,Quarter
645,2019-02-11,6091,25,40,2019,2,February,11,0,Monday,0,7,1
174,2019-11-03,718,9,3,2019,11,November,3,6,Sunday,1,44,4
106,2019-01-20,6592,25,11,2019,1,January,20,6,Sunday,1,3,1

## Extracting Time elapsed between dates

In [33]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 1, 20, 9, 20, 12, 249135)

In [36]:
inf = (today - date['date'])

In [37]:
inf.dt.days

0      2233
1      2715
2      2646
3      2348
4      2571
       ...
995    2661
996    2602
997    2450
998    2515
999    2289
Name: date, Length: 1000, dtype: int64

In [40]:
# Monthd Passed
np.round((inf) / np.timedelta64(1, 'M'), 0)

0      72.0
1      88.0
2      85.0
3      76.0
4      83.0
       ...
995    86.0
996    84.0
997    79.0
998    81.0
999    74.0
Name: date, Length: 1000, dtype: float64

In [41]:
#Time
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [42]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [43]:
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [46]:
time['hr'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time.sample(5)

,date,msg,hr,min,sec
250,2016-01-17 00:51:00,Сам в гостинице.скучно.27 киев.0937544418,0,51,0
126,2014-11-02 01:19:00,ПОЗНАКОМЛЮСЬ С ДЕВУШКОЙ . СЕЖУ В ТЮРЬМЕ. 068-4...,1,19,0
781,2014-05-07 00:28:00,Познакомлюсь с девушкой для инт.смс ммс,0,28,0
567,2014-09-01 23:32:00,ХОЧУ С СЕП/ПАР 095-02-005-33,23,32,0
960,2015-02-09 00:04:00,КРАСИВЫЙ П С АВТО ХОЧЕТ ИНТИМА ПО ТЕЛ С ДЕВУШК...,0,4,0

## Separate Time

In [48]:
time['timeOnly'] = time['date'].dt.time
time.sample(3)

,date,msg,hr,min,sec,timeOnly
637,2013-02-04 01:35:00,парень25л.из млс купит невесту б/у не придлога...,1,35,0,01:35:00
16,2015-10-19 22:52:00,КТО СДЕЛАЕТ ПАРНЮ МАССАЖ ДЕВ ИЛИ 2 СЕЙЧАС 099 ...,22,52,0,22:52:00
671,2014-03-08 22:52:00,Ищу парня для несерьезных отношений. Позвоню с...,22,52,0,22:52:00

## Separate Date

In [49]:
time['dateOnly'] = time['date'].dt.date
time.sample(3)

,date,msg,hr,min,sec,timeOnly,dateOnly
694,2014-02-07 00:58:00,заберу на машине девушек которые смелые ? кто ...,0,58,0,00:58:00,2014-02-07
755,2012-07-04 01:12:00,Обнаж М один дома ищу хочу Ж/Даму для встр!ммс...,1,12,0,01:12:00,2012-07-04
486,2015-02-05 00:12:00,ДЕВУШКА ПОЗНАКОМИТСЯ С ИНТЕРЕСНЫМ ПАРНЕМ ДЛЯ Д...,0,12,0,00:12:00,2015-02-05