In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('../__datasets__/train.csv')[['Age', 'Pclass', 'Fare', 'Survived']]
df.sample(4)

      Age  Pclass      Fare  Survived
796  49.0       1   25.9292         1
679  36.0       1  512.3292         1
729  25.0       3    7.9250         0
108  38.0       3    7.8958         0

In [4]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [5]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
X_train.sample(3)

      Age  Pclass     Fare
694  60.0       1  26.5500
681  27.0       1  76.7292
279  35.0       3  20.2500

In [37]:
knn = KNNImputer(n_neighbors=5, weights='distance')

In [38]:
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [39]:
pd.DataFrame(X_train_trf, columns=X_train.columns)

           Age  Pclass      Fare
0    45.500000     1.0   28.5000
1    23.000000     2.0   13.0000
2    32.000000     3.0    7.9250
3    26.000000     3.0    7.8542
4     6.000000     3.0   31.2750
..         ...     ...       ...
707  21.000000     3.0    7.6500
708  40.111111     1.0   31.0000
709  41.000000     3.0   14.1083
710  14.000000     1.0  120.0000
711  21.000000     1.0   77.2875

[712 rows x 3 columns]

In [40]:
lr = LogisticRegression()

lr.fit(X_train_trf, y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test, y_pred)

0.7374301675977654

In [41]:
# Comparision with SimpleImputer
si =SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)

X_test_trf2 = si.transform(X_test)

y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test, y_pred2)

0.7486033519553073